apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: logging
  labels:
    k8s-app: elasticsearch-logging
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: LoadBalancer       # LoadBalancer    NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 31001
  selector:
    k8s-app: elasticsearch-logging
