apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-server
    spec:
      containers:
      - image: mysql:5.7
        name: mariadb-server
        ports:
        - containerPort: 3306
          name: db
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "redhat"
        volumeMounts:
        - name: db-nfs
          mountPath: /var/lib/mysql
        #- name: conf
        #  mountPath: /etc/mysql
      volumes:
      - name: db-nfs
        nfs:
          server: 192.168.1.206
          path: "/bak/mariadb-server"
     # - name: conf
     #   nfs:
     #     server: 192.168.1.206
     #     path: "/data/zabbix/server/mysql-conf"
