apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.3.0
    component: "pushgateway"
    heritage: Tiller
    release: intent-skunk
  name: intent-skunk-prometheus-pushgateway
